export const popularFoods = [
  {
    id: 1,
    name: 'Chicken Fried Rice',
    price: 750,  
    rating: 4.3,              
    reviewCount: 5000,        
    deliveryTime: '15',     
    deliveryFee: 0,         
    image: '/api/placeholder/300/180', 
    categories: ['Rice', 'Sri Lankan', 'Seafood'], 
    offer: 'Spend LKR 3,500, Save LKR 800', 
    distance: 2.5
  },
  {
    id: 2,
    name: 'Devilled Chicken',
    rating: 4.6,
    reviewCount: 3200,
    deliveryTime: '20',
    deliveryFee: 50,
    image: '/api/placeholder/300/180',
    categories: ['Sri Lankan', 'Spicy', 'Chicken'],
  },
  {
    id: 3,
    name: 'Cheese Kottu',
    rating: 4.8,
    reviewCount: 8700,
    deliveryTime: '18',
    deliveryFee: 60,
    image: '/api/placeholder/300/180',
    categories: ['Sri Lankan', 'Street Food', 'Kottu'],
  },
  {
    id: 4,
    name: 'Vegetable Noodles',
    rating: 4.4,
    reviewCount: 2100,
    deliveryTime: '12',
    deliveryFee: 40,
    image: '/api/placeholder/300/180',
    categories: ['Chinese', 'Noodles', 'Vegetarian'],
  },
  {
    id: 5,
    name: 'Seafood Platter',
    rating: 4.7,
    reviewCount: 4500,
    deliveryTime: '25',
    deliveryFee: 100,
    image: '/api/placeholder/300/180',
    categories: ['Seafood', 'Sri Lankan', 'Special'],
  },
  {
    id: 6,
    name: 'Egg Roti with Curry',
    rating: 4.2,
    reviewCount: 1700,
    deliveryTime: '10',
    deliveryFee: 30,
    image: '/api/placeholder/300/180',
    categories: ['Sri Lankan', 'Street Food', 'Roti'],
  },
];


export const ggtest = [
  {
    id: 6,
    name: 'KFC',
    rating: 4.2,
    reviewCount: 15000,
    deliveryTime: '15',
    deliveryFee: 0,
    distance: 1.2,
    image: '/api/placeholder/300/180',
    categories: ['Fast Food', 'Chicken', 'Burgers'],
    offer: 'Spend LKR 3,500, Save LKR 800',
  },
  {
    id: 7,
    name: 'Neluma Awanhala',
    rating: 4.4,
    reviewCount: 3500,
    deliveryTime: '20',
    deliveryFee: 0,
    distance: 1.8,
    image: '/api/placeholder/300/180',
    categories: ['Sri Lankan', 'Traditional', 'Rice & Curry'],
  },
  {
    id: 8,
    name: 'Rasa Bojun',
    rating: 4.1,
    reviewCount: 2800,
    deliveryTime: '18',
    deliveryFee: 0,
    distance: 1.4,
    image: '/api/placeholder/300/180',
    categories: ['Sri Lankan', 'Rice & Curry', 'Kottu'],
  },
  {
    id: 9,
    name: 'BOJUNKA FOOD & BAKERS',
    rating: 4.3,
    reviewCount: 4200,
    deliveryTime: '25',
    deliveryFee: 0,
    distance: 2.0,
    image: '/api/placeholder/300/180',
    categories: ['Bakery', 'Pastries', 'Cakes'],
  },
];

export const nearbyRestaurants = [
  {
    id: 10,
    name: 'Pizza Hutgg',
    rating: 4.1,
    reviewCount: 12000,
    deliveryTime: '30',
    deliveryFee: 150,
    distance: 2.8,
    image: '/api/placeholder/300/180',
    categories: ['Pizza', 'Italian', 'Fast Food'],
  },
  {
    id: 11,
    name: 'Burger King',
    rating: 4.0,
    reviewCount: 8500,
    deliveryTime: '25',
    deliveryFee: 120,
    distance: 2.3,
    image: '/api/placeholder/300/180',
    categories: ['Burgers', 'Fast Food', 'American'],
  },
  {
    id: 12,
    name: 'Subway',
    rating: 4.2,
    reviewCount: 6800,
    deliveryTime: '20',
    deliveryFee: 100,
    distance: 1.9,
    image: '/api/placeholder/300/180',
    categories: ['Sandwiches', 'Healthy', 'Salads'],
  },
  {
    id: 13,
    name: 'Dominos Pizza',
    rating: 4.3,
    reviewCount: 9500,
    deliveryTime: '35',
    deliveryFee: 180,
    distance: 3.1,
    image: '/api/placeholder/300/180',
    categories: ['Pizza', 'Italian', 'Fast Food'],
  },
];
